### ISSUE TITLE
Default font does not have smoothing

### ISSUE THREAD

**Issue by raeesiqbal** [linuxdeepin/dde-desktop#1]
I'm not sure if this issue is in `dde-desktop` but the default serif font in Google Chrome is like in Windows XP and does not have smoothing. I'm not sure if you can see in the screenshot clearly but it doesnt look very good.
![deepinscreenshot20160211210722](https://cloud.githubusercontent.com/assets/10067728/12981697/a609e68c-d0d9-11e5-9db4-5e7854b5a46a.png)

**Comment by manateelazycat** [comment]
First, thanks for your suggestion.

Windows XP use serif and Deepin use Google/Adobe's "Source Han Sans SC" font, it's not render problem of system.

It's very different between serif and "Source Han Sans SC".
