### ISSUE TITLE
Can't install dde-next on Ubuntu 16.10

### ISSUE THREAD

**Issue by meilihao** [linuxdeepin/dde-desktop#11]
```
apt update
```

W: GPG 错误：http://packages.deepin.com/experimental experimental InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 820F938DCBE6D2D0

where is the pubkey?

**Comment by meilihao** [comment]
```
apt update
```

W: GPG 错误：http://packages.deepin.com/experimental experimental InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 820F938DCBE6D2D0

where is the pubkey?

**Comment by BLumia** [comment]
:joy: 现在好像已经没有 dde-next 了，先关掉了
