### ISSUE TITLE
android-studio在dock的图标是黑色的

### ISSUE THREAD

**Issue by ListenerRi** [linuxdeepin/dde-desktop#12]
如下图所示:
![20170219214723](https://cloud.githubusercontent.com/assets/7995379/23102930/10884f82-f6ed-11e6-9314-28adad2149c2.png)

**Comment by SuperSuperSuperSuper5** [comment]
没人管这个仓库了感觉哈哈哈

**Comment by SalahAdDin** [comment]
Same for GtiKraken.

**Comment by sbwtw** [comment]
That's a confirmed bug. It's a problem with Qt' svg render. there is no good solution yet.

**Comment by SalahAdDin** [comment]
What says the `Qt` developers staff?

**Comment by sbwtw** [comment]
Qt svg module only support a part of svg standard specifiction. not fully implemented.
you can see this bug: https://bugs.documentfoundation.org/show_bug.cgi?id=99395

**Comment by SalahAdDin** [comment]
In this case, won't be a properly solution in a near time, right?

**Comment by sbwtw** [comment]
@SalahAdDin Yes, but we have a plan to switch to `cario` to render svg image in future.

**Comment by SalahAdDin** [comment]
Which engine use `gnome` and `kde`.
