### ISSUE TITLE
Chrome - Use system title bar and borders

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxdeepin/dde-desktop#18]
1. Problem/Advice description
By using the system title bar and the borders it gets totally different and out of layout.
2. How to reproduce the problem
When activating use the system title bar and the borders.
3. Problem reproduce frequency
When activating use the system title bar and the borders.
Operating system :deepin
Desktop environment :dde

http://feedback.deepin.org/feedback/detail/2515

[deepin-feedback-cli-Deepin-15.4-all-20170328-142652.tar.gz](https://github.com/linuxdeepin/dde-desktop/files/877416/deepin-feedback-cli-Deepin-15.4-all-20170328-142652.tar.gz)
![deepinscreenshot20170328142020](https://cloud.githubusercontent.com/assets/8754997/24433098/cdff0958-13fc-11e7-8f13-9414e2d51f9c.png)

**Comment by SalahAdDin** [comment]
I have these problem with Chrome:
![capturadeepinchrome](https://cloud.githubusercontent.com/assets/5034215/26038656/e03ebf9e-3915-11e7-90a5-c2e0a876049d.png)

But i have with Firefox:
![capturafirefoxdeepin](https://cloud.githubusercontent.com/assets/5034215/26038657/e1ead968-3915-11e7-82c6-533e61c10e68.png)

**Comment by GabrielMGitHub** [comment]
It has not been verified.
