### ISSUE TITLE
Desktop Computer and Trash icons unremovable

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-desktop#2]
<a href="https://github.com/eloc574"><img src="https://avatars.githubusercontent.com/u/5067255?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @eloc574**
_Saturday Sep 06, 2014 at 20:21 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/34_

----

Both in Efficient mode and Classic mode. 
Trash icon also undockable in Fashion mode.
Was not able to find any way to remove these icons.

**Comment by Esjitu** [comment]
Same problem here. Deepin's stylish looks were what grabbed my attention to begin with, so not being able to have a clean icon-free desktop detracts from that IMO.

**Comment by manateelazycat** [comment]
We have fixed this problem that user can remove computer and trash icons from desktop if user like. ;)

Tha
