### ISSUE TITLE
归档管理器无法直接拖动文件到桌面

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-desktop#3]
<a href="https://github.com/zhuzilinuser"><img src="https://avatars.githubusercontent.com/u/12298476?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @zhuzilinuser**
_Wednesday Feb 24, 2016 at 12:10 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/254_

----

但是可以将文件拖动到鹦鹉螺里面解压 【论坛一个人发帖了，我就自己试了试，不能直接拖动文件到桌面进行解压操作，而且似乎拖动到桌面以后，桌面还会卡一下。

**Comment by manateelazycat** [comment]
这个问题已经在最新版的 deepin-desktop 中修复， 请更新到最新版。 

谢谢您的报告！
