### ISSUE TITLE
Installing deepin DDE prevents Gnome3 to access "accounts settings"

### ISSUE THREAD

**Issue by srarty** [linuxdeepin/dde-desktop#33]
I am running the latest update of Arch Linux and Gnome3. Just installed Deepin Desktop Environment and it works fine, but when I use Gnome environment, I can't access the user settings. Something was damaged when deepin was installed. User settings in Deepin work fine.

**Comment by jouyouyun** [comment]
What's happen?

**Comment by srarty** [comment]
Somehow installing DDE as a second desktop environment did something to Gnome3. So, I have been working with Gnome3 just fine, but I recently installed DDE from the AUR repository and it works alright. But when I start Arch on Gnome3, I can't access the account setup.

So I'm on Gnome3, I go to "settings" -> "account settings" and then nothing happens, it looks like it's going to do something but then it stops responding. After trying to open "account settings", I cannot even access the general "settings" window anymore (I have to reboot).

I tried uninstalling DDE and reinstalling Gnome, but nothing works. Everything else seems to be working fine.

I do not know how to explain the issue more clearly, I hope this is enough.

Thanks!!!

**Comment by jouyouyun** [comment]
I install gnome 3.22.3 on deepin and tested it, no problem found.

**Comment by srarty** [comment]
Yeah, that has nothing to do with my issue. 

1) Working Arch Linux distribution 
2) Installed Gnome3, no problems found.
3) Installed Deepin Desktop Environment on Arch Linux, as an alternative DE. Runs fine.
4) Run Gnome3 after testing DDE. Gnome3 now has problems accessing the Accounts Settings

**Comment by felixonmars** [comment]
How did you install DDE from AUR? AFAIK it's in the [community] repository.

I cannot reproduce your issue on my Arch, though. I have quite a few DEs installed at the same time, including Gnome 3 and DDE. The account settings of gnome works fine here.

**Comment by srarty** [comment]
Yes, you're right. I actually installed it from the community repo. I used yaourt instead of pacman, but it was in the community repository.

Would you mind trying to change the user's picture from DDE, then rebooting on Gnome3 and see if you can access the settings? That's all I did. 

Anyway, thanks for your answers, I am aware that this might not be the place to post my issue, I will request help in an Arch forum instead.

**Comment by jouyouyun** [comment]
@srarty I change the background in deepin, then reboot to gnome. But gnome account settings work fine.

**Comment by srarty** [comment]
Thanks @jouyouyun. It got fixed suddenly after the last update I did (-Syu). I don't know what caused the issue or what fixed it, but it's not there anymore.
