### ISSUE TITLE
Multiple monitors breaks desktop right-click menu

### ISSUE THREAD

**Issue by V3XATI0N** [linuxdeepin/dde-desktop#35]
When I use more than 2 monitors, I lose desktop icons and the ability to access desktop right-click commands. Which is lame.

**Comment by damien122** [comment]
I have the same problem with 3 displays on my pc.

**Comment by damien122** [comment]
here is the same problem https://github.com/linuxdeepin/developer-center/issues/337

**Comment by damien122** [comment]
after the latest update my problem was fixed. @V3XATI0N do you still have this problem?

**Comment by V3XATI0N** [comment]
Recent updates also resolved this for me. But there are lingering issues with multiple monitors, specifically:

- Desktop icons and the Deepin Dock can only be placed on the primary monitor, which is annoying.

- Deepin-Screenshot and Deepin Screen Recorder will only capture images/video from the primary monitor, which is a major flaw.

- The screen arrangement utility is designed well but tends to work a little clumsily, causing screens to overlap each other unless a considerable gap is placed between them.

**Comment by damien122** [comment]
I have the same issues but in my opinion this are separate issues which should be opened and this issue can be closed.
