### ISSUE TITLE
xkill shortcut

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-desktop#4]
I'm use kde for long years and migrate for Deepin, in kde shortcut Esc+Alt+Ctrl open xkill, this is simple, but very good feature.

Maybe if add this feature in default configuration of Deepin, and maybe adding one alert about usage of this feature.

Sorry for my bad english.

**Comment by fasheng** [comment]
Thanks for the advice, I move it to https://github.com/linuxdeepin/developer-center/issues so more developers could see it :smiley:
