### ISSUE TITLE
ctrl+shift+e strange behaviour

### ISSUE THREAD

**Issue by core01** [linuxdeepin/dde-desktop#44]
Deepin OS 15.7

At this gif I pressed ctrl+shift+e several times.
![deepin-screen-recorder_gedit_20180926094347](https://user-images.githubusercontent.com/2903772/46056092-d04ceb80-c170-11e8-9c75-95b240685654.gif)

How to disable this hotkey system-wide to start using ctrl+shift+e inside VSCode or another applications?

**Comment by jouyouyun** [comment]
You should to find out which app grabbed the hotkey 'ctrl+shift+e', then disable it.
DDE not grab this hotkey.

**Comment by core01** [comment]
@jouyouyun how I can find it ? This behavior occurs on clean installed Deepin OS 15.7
I guess it is not app problem it is xorg keyboard or gnome or gkt problem

**Comment by core01** [comment]
Solution is found, described here https://superuser.com/a/1334194
