### ISSUE TITLE
DDE 的启动器热键呼出不在最前面

### ISSUE THREAD

**Issue by danny2jenny** [linuxdeepin/dde-desktop#5]
15.2 全新安装，很多时候用 window热键或者是窗口区域呼出启动器，启动器不在最前面，不能显示，被其他的全屏窗口遮盖了。

**Comment by fasheng** [comment]
15.3应该会有改善~

**Comment by manateelazycat** [comment]
15.3 应该没有问题了，　如果还有问题请重新打开。

@danny2jenny 非常感谢你反馈。　;)
