### ISSUE TITLE
Is there a keyboard shortcut or setting for cycling through workspaces?

### ISSUE THREAD

**Issue by s7dhansh** [linuxdeepin/dde-desktop#51]
Either, a setting that can cause Win+Right to go to first workspace if currently on the last one.
Or a command to cycle through workspaces which can be assigned a custom key?

**Comment by BLumia** [comment]
You can get the shortcut from *Control Center* > *Shortcuts*, I changed the default shortcut so I'm not sure but the default shortcut for switching workspaces currently should be <kbd>Ctrl + Alt + Left/Right</kbd>.

**Comment by BLumia** [comment]
further discussion goes here: https://github.com/linuxdeepin/developer-center/issues/1035

Closing.
