### ISSUE TITLE
The deepin desktop enviroment is very small on  high-resolution (high-DPI) screens

### ISSUE THREAD

**Issue by marek-lach** [linuxdeepin/dde-desktop#54]
... For example on the Surface Pro, with a resolution of 2160x1440 the whole desktop environment just does not scale itself at all, and stays very small, which makes it then impossible to use.

**Comment by BLumia** [comment]
What if you change the DPI scale value from the control center? btw `dde-desktop` is a part of `dde-file-manager`, this repo is no longer used actually..
